char const *countries[195] = {
    "Afeghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo (Congo-Brazzaville)",
    "Costa Rica",
    "Côte d'Ivoire",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czechia (Czech Republic)",
    "Democratic Republic of the Congo",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini (fmr. Swaziland)",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Holy See",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar (formerly Burma)",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine State",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States of America",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe",
};

char const *colors[195] = {
    "Black",
    "White",
    "Gray",
    "Light Gray",
    "Dark Gray",
    "Silver",
    "Slate Gray",
    "Charcoal",
    "Platinum",
    "Ivory",
    "Beige",
    "Cream",
    "Brown",
    "Light Brown",
    "Dark Brown",
    "Chocolate",
    "Coffee",
    "Caramel",
    "Sand",
    "Amber",
    "Honey",
    "Ochre",
    "Sienna",
    "Terracotta",
    "Rust",
    "Copper",
    "Bronze",
    "Gold",
    "Goldenrod",
    "Khaki",
    "Tan",
    "Wheat",
    "Linen",
    "Peach",
    "Apricot",
    "Coral",
    "Orange",
    "Dark Orange",
    "Light Orange",
    "Pumpkin",
    "Tangerine",
    "Fire",
    "Red",
    "Dark Red",
    "Light Red",
    "Crimson",
    "Scarlet",
    "Burgundy",
    "Wine",
    "Cherry",
    "Strawberry",
    "Raspberry",
    "Pink",
    "Hot Pink",
    "Baby Pink",
    "Light Pink",
    "Dark Pink",
    "Salmon",
    "Magenta",
    "Fuchsia",
    "Lilac",
    "Lavender",
    "Violet",
    "Purple",
    "Dark Purple",
    "Light Purple",
    "Plum",
    "Grape",
    "Indigo",
    "Blue",
    "Dark Blue",
    "Light Blue",
    "Navy Blue",
    "Sky Blue",
    "Baby Blue",
    "Cobalt Blue",
    "Turquoise",
    "Royal Blue",
    "Petroleum Blue",
    "Teal",
    "Cyan",
    "Aquamarine",
    "Azure",
    "Periwinkle",
    "Mint Blue",
    "Powder Blue",
    "Steel Blue",
    "Ice Blue",
    "Ocean Blue",
    "Denim Blue",
    "Forest Green",
    "Green",
    "Light Green",
    "Dark Green",
    "Olive",
    "Moss Green",
    "Lime",
    "Lime Green",
    "Neon Green",
    "Sea Green",
    "Emerald",
    "Jade",
    "Mint",
    "Pine Green",
    "Bottle Green",
    "Grass Green",
    "Fern Green",
    "Spring Green",
    "Chartreuse",
    "Avocado",
    "Apple Green",
    "Shamrock Green",
    "Kelly Green",
    "Hunter Green",
    "Yellow",
    "Light Yellow",
    "Dark Yellow",
    "Gold Yellow",
    "Neon Yellow",
    "Pale Yellow",
    "Canary Yellow",
    "Lemon Yellow",
    "Mustard",
    "Flax",
    "Golden Beige",
    "Sunshine Yellow",
    "Daffodil",
    "Champagne",
    "Pearl",
    "Vanilla",
    "Sand Yellow",
    "Topaz",
    "Amber Yellow",
    "Marigold",
    "Sunset Orange",
    "Brick Red",
    "Mahogany",
    "Chestnut",
    "Cinnamon",
    "Clay",
    "Burnt Orange",
    "Burnt Sienna",
    "Burnt Umber",
    "Sepia",
    "Eggplant",
    "Mulberry",
    "Amethyst",
    "Heather",
    "Thistle",
    "Orchid",
    "Mauve",
    "Cerulean",
    "Prussian Blue",
    "Midnight Blue",
    "Arctic Blue",
    "Glacier Blue",
    "Iceberg",
    "Pale Blue",
    "Robin Egg Blue",
    "Baby Blue Eyes",
    "Capri",
    "Cornflower Blue",
    "Dodger Blue",
    "Deep Sky Blue",
    "Light Sky Blue",
    "Aqua",
    "Seafoam",
    "Seafoam Green",
    "Pale Green",
    "Pastel Green",
    "Spring Bud",
    "Celadon",
    "Artichoke",
    "Basil Green",
    "Kelly Green",
    "Olive Drab",
    "Camouflage Green",
    "Army Green",
    "Khaki Green",
    "Pistachio",
    "Pear Green",
    "Honeydew",
    "Snow",
    "Ghost White",
    "Floral White",
    "Antique White",
    "Old Lace",
    "White Smoke",
    "Seashell",
    "Mint Cream",
    "Ivory White",
    "Azure White",
    "Alice Blue",
    "Beige White",
    "Grayish White",
};
